"""E2E regression for #50 + #74 — image-loading resilience on the review tab.

#50: our own forestshop-CDN product image can go stale (renamed/removed product
photo) — the card must degrade to a clean 'bez obrázka' placeholder instead of a
broken-image icon.

#74: a fast scroll through a large filter (e.g. ~1800+ 'Napárované' cards) makes
MANY cards' supplier-image galleries cross the IntersectionObserver's 300px
rootMargin within the same tick. Live-reproduced on the deployed app (2026-07-22,
'Všetky' filter + a fast scroll through ~2857 cards): a burst of concurrent
/api/images scrapes overwhelmed the backend, surfacing as ~30 'Failed to load
resource: 524' (Cloudflare edge timeout) console errors. The client now queues
those fetches through IMG_FETCH_CONCURRENCY so the backend never sees more than a
few in flight at once.

NOTE on console assertions here: Chrome logs 'Failed to load resource: <status>'
for ANY failed resource load (an <img>, a fetch — doesn't matter) — this is
generated by the browser's own network stack and is NOT suppressible from JS,
onerror included (verified live on the deployed app: an <img> WITH an onerror
handler produced the identical console line as an otherwise-identical <img>
WITHOUT one). So a genuinely-broken image can never make `console == []` true —
only that NO OTHER, unexpected error appears alongside it, exactly like
test_auth.py's `_PROVOKED` pattern for a deliberately-provoked 401/403."""
import re


_PROVOKED_404 = re.compile(r"Failed to load resource: .*missing-image-404-test\.jpg")


def _unexpected(console):
    return [m for m in console if not _PROVOKED_404.search(m)]


def test_broken_own_image_degrades_to_placeholder(page, imgfail_server):
    """#50: renderCard's own-image <img> now has onerror → swaps to '.noimg' on a
    genuinely failed load (RED before this fix: no onerror, the broken <img>
    element — and the browser icon — stays in the DOM forever)."""
    console = []
    page.on("console", lambda m: console.append(f"[{m.type}] {m.text}")
            if m.type in ("error", "warning") else None)

    page.goto(imgfail_server + "/?tab=review")
    page.wait_for_selector('[data-testid="version"]')
    page.wait_for_selector(".card")

    imgs_box = page.locator(".card .side.left .imgs")
    page.wait_for_selector(".card .side.left .imgs .noimg")
    assert imgs_box.locator("img").count() == 0, "broken <img> element still in DOM"
    assert imgs_box.locator(".noimg").inner_text() == "bez obrázka"

    # the ONE deliberately-provoked 404 (our own broken fixture URL) is the only
    # allowed console entry — Chrome logs it unconditionally, onerror cannot
    # suppress it (see module docstring); anything else fails the test.
    assert _unexpected(console) == [], f"console not clean: {console}"


def test_gallery_image_fetch_concurrency_is_capped(page, imgflood_server):
    """#74: N matched cards' galleries all cross the rootMargin at once (tall
    viewport, no scrolling needed) — the simulated 'supplier' server must never
    see more than IMG_FETCH_CONCURRENCY concurrent requests, and all N must
    eventually load (nothing silently dropped by the queue)."""
    state, n = imgflood_server.state, imgflood_server.n
    # Tall viewport so every one of the N short cards sits within the
    # IntersectionObserver's rootMargin without any scrolling — deterministic.
    page.set_viewport_size({"width": 1280, "height": 4000})
    page.goto(imgflood_server + "/?tab=review")
    page.wait_for_selector('[data-testid="version"]')
    page.wait_for_selector(".card")

    page.wait_for_function(
        "() => document.querySelectorAll('.imgs.loading').length === 0",
        timeout=15000)

    assert state.total == n, f"expected all {n} supplier fetches, got {state.total}"
    assert state.max_active <= 4, f"concurrency cap violated: max_active={state.max_active}"
